package com.example.utils

import android.graphics.Bitmap
import java.io.File
import java.io.FileOutputStream
import java.nio.charset.StandardCharsets
import java.util.Locale

object PclmGenerator {

    /**
     * 手动构建一个符合 HP PCLm 标准的 PDF 文件
     * 核心：
     * 1. 注入 %PCLm 1.0 头部
     * 2. 使用 JPEG (/DCTDecode) 编码图片，避开不支持的 FlateDecode
     */
    fun generatePclmPdf(bitmap: Bitmap, outputFile: File): File {
        val fos = FileOutputStream(outputFile)
        val writer = PdfWriter(fos)

        // 1. PDF Header (必须包含 PCLm 签名)
        writer.writeLine("%PDF-1.7")
        writer.writeLine("%PCLm 1.0") // 👈 这一行是让打印机动起来的关键
        writer.writeLine("%Generated by CustomApp")

        // 准备图片数据 (压缩为 JPEG)
        val jpgStream = java.io.ByteArrayOutputStream()
        // 质量 80 足够清晰且文件小，HP 105a 内存小，不要发太大的包
        bitmap.compress(Bitmap.CompressFormat.JPEG, 80, jpgStream) 
        val imgData = jpgStream.toByteArray()
        val width = bitmap.width
        val height = bitmap.height

        // --- 开始构建 PDF 对象 (标准的 1页 PDF 结构) ---

        // Object 1: Catalog (目录)
        val catalogObjId = writer.startObject()
        writer.writeLine("<< /Type /Catalog /Pages 2 0 R >>")
        writer.endObject()

        // Object 2: Page Tree (页面树)
        val pageTreeObjId = writer.startObject()
        writer.writeLine("<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
        writer.endObject()

        // Object 3: Page (页面定义) - A4 尺寸
        // MediaBox [0 0 595 842] 是 A4 @ 72DPI
        // 我们需要让图片铺满这个区域
        val pageObjId = writer.startObject()
        writer.writeLine("<<")
        writer.writeLine("  /Type /Page")
        writer.writeLine("  /Parent 2 0 R")
        writer.writeLine("  /MediaBox [0 0 595 842]") 
        writer.writeLine("  /Resources << /XObject << /Im0 4 0 R >> >>") // Im0 是图片引用
        writer.writeLine("  /Contents 5 0 R") // 页面绘制指令
        writer.writeLine(">>")
        writer.endObject()

        // Object 4: Image XObject (这是实际的图片数据)
        // 使用 /DCTDecode 表示 JPEG，这是 PCLm 支持的标准格式
        val imageObjId = writer.startObject()
        writer.writeLine("<<")
        writer.writeLine("  /Type /XObject")
        writer.writeLine("  /Subtype /Image")
        writer.writeLine("  /Width $width")
        writer.writeLine("  /Height $height")
        writer.writeLine("  /ColorSpace /DeviceRGB") // 黑白打印机通常也能处理 RGB JPEG，会自动转灰度
        writer.writeLine("  /BitsPerComponent 8")
        writer.writeLine("  /Filter /DCTDecode") // 👈 关键：告诉打印机这是 JPEG
        writer.writeLine("  /Length ${imgData.size}")
        writer.writeLine(">>")
        writer.writeLine("stream")
        writer.flush() // 写入流之前先刷新缓冲
        fos.write(imgData) // 直接写入 JPEG 二进制数据
        writer.writeLine("") // 换行
        writer.writeLine("endstream")
        writer.endObject()

        // Object 5: Content Stream (绘制指令)
        // q = save state, 595 0 0 842 0 0 cm = 缩放图片铺满 A4, /Im0 Do = 画图, Q = restore
        val content = "q 595 0 0 842 0 0 cm /Im0 Do Q"
        val contentObjId = writer.startObject()
        writer.writeLine("<< /Length ${content.length} >>")
        writer.writeLine("stream")
        writer.writeLine(content)
        writer.writeLine("endstream")
        writer.endObject()

        // --- 写入 XREF 表和 Trailer (文件尾) ---
        val xrefOffset = writer.bytesWritten
        writer.writeLine("xref")
        writer.writeLine("0 6") // 0 到 5，共6个对象 (包含0号空对象)
        writer.writeLine("0000000000 65535 f ")
        
        // 写入每个对象的偏移量
        for (offset in writer.objectOffsets) {
            val offsetStr = String.format(Locale.US, "%010d 00000 n ", offset)
            writer.writeLine(offsetStr)
        }

        writer.writeLine("trailer")
        writer.writeLine("<< /Size 6 /Root 1 0 R >>")
        writer.writeLine("startxref")
        writer.writeLine("$xrefOffset")
        writer.writeLine("%%EOF")

        fos.close()
        return outputFile
    }

    // --- 内部辅助类：帮我们计算字节偏移量 ---
    private class PdfWriter(private val stream: FileOutputStream) {
        var bytesWritten: Long = 0
        val objectOffsets = mutableListOf<Long>()

        fun startObject(): Int {
            objectOffsets.add(bytesWritten)
            val id = objectOffsets.size // 这里的 ID 其实是 index + 1 ? 不，index 0 是 obj 1
            // 修正：Obj ID 从 1 开始，所以 index 0 对应 offset of Obj 1
            writeLine("${objectOffsets.size} 0 obj")
            return objectOffsets.size
        }

        fun endObject() {
            writeLine("endobj")
        }

        fun writeLine(s: String) {
            val bytes = (s + "\n").toByteArray(StandardCharsets.US_ASCII)
            stream.write(bytes)
            bytesWritten += bytes.size
        }
        
        fun flush() {
            stream.flush()
        }
    }
}